version: "3"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config/jellyfin_config:/config
      - /home/matiargs/media/tvshows:/data/tvshows
      - /home/matiargs/media/movies:/data/movies
      - /home/matiargs/media/anime:/data/anime
    ports:
      - 8096:8096
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config/sonarr_config:/config
      - /home/matiargs/media/anime:/anime
      - /home/matiargs/media/tvshows:/tvshows
      - /home/matiargs/media/transmission/downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config/radarr_config:/config
      - /home/matiargs/media/transmission/downloads/complete:/downloads/complete
      - /home/matiargs/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./config/bazarr_config:/config
      - /home/matiargs/media/movies:/movies #optional
      - /home/matiargs/media/tvshows:/tvshows #optional
      - /home/matiargs/media/anime:/anime
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - 5055:5055
    volumes:
      - ./config/jellyseerr_config:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
